### PR TITLE
Updating packages

### PR DESCRIPTION
**Pull request by kkodali**
Updating packages and eslint support extensions, also updated preset to env from es2015

### CODE REVIEW

**Comment by kkodali** [comment]
Updating packages and eslint support extensions, also updated preset from es2015 to env

**Comment by kkodali** [comment]
@armsteadj1  Please check the changes before you pull in!! I see there are no conflicts but npm test didn't execute on my local :( 
1. I updated presets in babelrc to env from es2015 as its outdated!
2. we also need to configure a preset to optionally accept webpack 3.0.0 || webpack 4.0.0 as  url-loader is throwing a peer dependency warning.

**Comment by armsteadj1** [comment]
Sounds good! I will be back at my laptop a bit later today and will pull it down and check it out. Thanks!

**Comment by armsteadj1** [comment]
This has been merged in and deployed as version 1.1.1, let me know if you have any issues!

**Pull request merged**
